// <auto-generated />
// This file was generated by R4Mvc.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the r4mvc.json file (i.e. the settings file), save it and run the generator tool again.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo.Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using R4Mvc;

[GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
public static partial class MVC
{
    static readonly R4Mvc.UsersAreaClass s_Users = new R4Mvc.UsersAreaClass();
    public static R4Mvc.UsersAreaClass Users => s_Users;
    public static readonly OnAuth.Users.Web.Controllers.HomeController Home = new OnAuth.Users.Web.Controllers.R4MVC_HomeController();
    public static readonly R4Mvc.SharedController Shared = new R4Mvc.SharedController();
}

namespace R4Mvc
{
    [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy()
        {
        }

        public static Dummy Instance = new Dummy();
    }

    [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
    public partial class SharedController
    {
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames => s_ViewNames;
            public class _ViewNamesClass
            {
                public readonly string Error = "Error";
                public readonly string PagingPartial = "PagingPartial";
                public readonly string _CookieConsentPartial = "_CookieConsentPartial";
                public readonly string _Layout = "_Layout";
                public readonly string _LoginPartial = "_LoginPartial";
                public readonly string _ValidationScriptsPartial = "_ValidationScriptsPartial";
            }

            public readonly string Error = "~/Views/Shared/Error.cshtml";
            public readonly string PagingPartial = "~/Views/Shared/PagingPartial.cshtml";
            public readonly string _CookieConsentPartial = "~/Views/Shared/_CookieConsentPartial.cshtml";
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string _LoginPartial = "~/Views/Shared/_LoginPartial.cshtml";
            public readonly string _ValidationScriptsPartial = "~/Views/Shared/_ValidationScriptsPartial.cshtml";
        }

        static readonly ViewsClass s_Views = new ViewsClass();
        public ViewsClass Views => s_Views;
    }

    [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
    public partial class UsersAreaClass
    {
        public readonly string Name = "Users";
        public readonly OnAuth.Users.Web.Areas.Users.Home.HomeController Home = new OnAuth.Users.Web.Areas.Users.Home.R4MVC_HomeController();
        public readonly OnAuth.Users.Web.Areas.Users.Roles.RolesController Roles = new OnAuth.Users.Web.Areas.Users.Roles.R4MVC_RolesController();
    }
}

[GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
public static partial class Links
{
    public static partial class css
    {
        public static string site_css = "~/css/site.css";
        public static string site_min_css = "~/css/site.min.css";
    }

    public static partial class images
    {
        public static string banner1_svg = "~/images/banner1.svg";
        public static string banner2_svg = "~/images/banner2.svg";
        public static string banner3_svg = "~/images/banner3.svg";
        public static string banner4_svg = "~/images/banner4.svg";
    }

    public static partial class js
    {
        public static string site_js = "~/js/site.js";
        public static string site_min_js = "~/js/site.min.js";
    }

    public static partial class lib
    {
        public static partial class bootstrap
        {
            public static partial class dist
            {
                public static partial class css
                {
                    public static string bootstrap_theme_css = "~/lib/bootstrap/dist/css/bootstrap-theme.css";
                    public static string bootstrap_theme_css_map = "~/lib/bootstrap/dist/css/bootstrap-theme.css.map";
                    public static string bootstrap_theme_min_css = "~/lib/bootstrap/dist/css/bootstrap-theme.min.css";
                    public static string bootstrap_theme_min_css_map = "~/lib/bootstrap/dist/css/bootstrap-theme.min.css.map";
                    public static string bootstrap_css = "~/lib/bootstrap/dist/css/bootstrap.css";
                    public static string bootstrap_css_map = "~/lib/bootstrap/dist/css/bootstrap.css.map";
                    public static string bootstrap_min_css = "~/lib/bootstrap/dist/css/bootstrap.min.css";
                    public static string bootstrap_min_css_map = "~/lib/bootstrap/dist/css/bootstrap.min.css.map";
                }

                public static partial class fonts
                {
                    public static string glyphicons_halflings_regular_eot = "~/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.eot";
                    public static string glyphicons_halflings_regular_svg = "~/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.svg";
                    public static string glyphicons_halflings_regular_ttf = "~/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf";
                    public static string glyphicons_halflings_regular_woff = "~/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.woff";
                    public static string glyphicons_halflings_regular_woff2 = "~/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2";
                }

                public static partial class js
                {
                    public static string bootstrap_js = "~/lib/bootstrap/dist/js/bootstrap.js";
                    public static string bootstrap_min_js = "~/lib/bootstrap/dist/js/bootstrap.min.js";
                    public static string npm_js = "~/lib/bootstrap/dist/js/npm.js";
                }
            }

            public static string _bower_json = "~/lib/bootstrap/.bower.json";
            public static string LICENSE = "~/lib/bootstrap/LICENSE";
        }

        public static partial class jquery
        {
            public static partial class dist
            {
                public static string jquery_js = "~/lib/jquery/dist/jquery.js";
                public static string jquery_min_js = "~/lib/jquery/dist/jquery.min.js";
                public static string jquery_min_map = "~/lib/jquery/dist/jquery.min.map";
            }

            public static partial class validation
            {
                public static partial class dist
                {
                    public static string additional_methods_js = "~/lib/jquery-validation/dist/additional-methods.js";
                    public static string additional_methods_min_js = "~/lib/jquery-validation/dist/additional-methods.min.js";
                    public static string jquery_validate_js = "~/lib/jquery-validation/dist/jquery.validate.js";
                    public static string jquery_validate_min_js = "~/lib/jquery-validation/dist/jquery.validate.min.js";
                }

                public static partial class unobtrusive
                {
                    public static string _bower_json = "~/lib/jquery-validation-unobtrusive/.bower.json";
                    public static string jquery_validate_unobtrusive_js = "~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js";
                    public static string jquery_validate_unobtrusive_min_js = "~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js";
                    public static string LICENSE_txt = "~/lib/jquery-validation-unobtrusive/LICENSE.txt";
                }

                public static string _bower_json = "~/lib/jquery-validation/.bower.json";
                public static string LICENSE_md = "~/lib/jquery-validation/LICENSE.md";
            }

            public static partial class validation_unobtrusive
            {
                public static string _bower_json = "~/lib/jquery-validation-unobtrusive/.bower.json";
                public static string jquery_validate_unobtrusive_js = "~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js";
                public static string jquery_validate_unobtrusive_min_js = "~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js";
                public static string LICENSE_txt = "~/lib/jquery-validation-unobtrusive/LICENSE.txt";
            }

            public static string _bower_json = "~/lib/jquery/.bower.json";
            public static string LICENSE_txt = "~/lib/jquery/LICENSE.txt";
        }

        public static partial class jquery_validation
        {
            public static partial class dist
            {
                public static string additional_methods_js = "~/lib/jquery-validation/dist/additional-methods.js";
                public static string additional_methods_min_js = "~/lib/jquery-validation/dist/additional-methods.min.js";
                public static string jquery_validate_js = "~/lib/jquery-validation/dist/jquery.validate.js";
                public static string jquery_validate_min_js = "~/lib/jquery-validation/dist/jquery.validate.min.js";
            }

            public static partial class unobtrusive
            {
                public static string _bower_json = "~/lib/jquery-validation-unobtrusive/.bower.json";
                public static string jquery_validate_unobtrusive_js = "~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js";
                public static string jquery_validate_unobtrusive_min_js = "~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js";
                public static string LICENSE_txt = "~/lib/jquery-validation-unobtrusive/LICENSE.txt";
            }

            public static string _bower_json = "~/lib/jquery-validation/.bower.json";
            public static string LICENSE_md = "~/lib/jquery-validation/LICENSE.md";
        }

        public static partial class jquery_validation_unobtrusive
        {
            public static string _bower_json = "~/lib/jquery-validation-unobtrusive/.bower.json";
            public static string jquery_validate_unobtrusive_js = "~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js";
            public static string jquery_validate_unobtrusive_min_js = "~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js";
            public static string LICENSE_txt = "~/lib/jquery-validation-unobtrusive/LICENSE.txt";
        }
    }

    public static string favicon_ico = "~/favicon.ico";
}

[GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
internal partial class R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult : ActionResult, IR4MvcActionResult
{
    public R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(string area, string controller, string action, string protocol = null)
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }

    public string Controller
    {
        get;
        set;
    }

    public string Action
    {
        get;
        set;
    }

    public string Protocol
    {
        get;
        set;
    }

    public RouteValueDictionary RouteValueDictionary
    {
        get;
        set;
    }
}

[GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
internal partial class R4Mvc_Microsoft_AspNetCore_Mvc_JsonResult : JsonResult, IR4MvcActionResult
{
    public R4Mvc_Microsoft_AspNetCore_Mvc_JsonResult(string area, string controller, string action, string protocol = null): base (null)
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }

    public string Controller
    {
        get;
        set;
    }

    public string Action
    {
        get;
        set;
    }

    public string Protocol
    {
        get;
        set;
    }

    public RouteValueDictionary RouteValueDictionary
    {
        get;
        set;
    }
}

[GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
internal partial class R4Mvc_Microsoft_AspNetCore_Mvc_ContentResult : ContentResult, IR4MvcActionResult
{
    public R4Mvc_Microsoft_AspNetCore_Mvc_ContentResult(string area, string controller, string action, string protocol = null)
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }

    public string Controller
    {
        get;
        set;
    }

    public string Action
    {
        get;
        set;
    }

    public string Protocol
    {
        get;
        set;
    }

    public RouteValueDictionary RouteValueDictionary
    {
        get;
        set;
    }
}

[GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
internal partial class R4Mvc_Microsoft_AspNetCore_Mvc_FileResult : FileResult, IR4MvcActionResult
{
    public R4Mvc_Microsoft_AspNetCore_Mvc_FileResult(string area, string controller, string action, string protocol = null): base (null)
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }

    public string Controller
    {
        get;
        set;
    }

    public string Action
    {
        get;
        set;
    }

    public string Protocol
    {
        get;
        set;
    }

    public RouteValueDictionary RouteValueDictionary
    {
        get;
        set;
    }
}

[GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
internal partial class R4Mvc_Microsoft_AspNetCore_Mvc_RedirectResult : RedirectResult, IR4MvcActionResult
{
    public R4Mvc_Microsoft_AspNetCore_Mvc_RedirectResult(string area, string controller, string action, string protocol = null): base (" ")
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }

    public string Controller
    {
        get;
        set;
    }

    public string Action
    {
        get;
        set;
    }

    public string Protocol
    {
        get;
        set;
    }

    public RouteValueDictionary RouteValueDictionary
    {
        get;
        set;
    }
}

[GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
internal partial class R4Mvc_Microsoft_AspNetCore_Mvc_RedirectToActionResult : RedirectToActionResult, IR4MvcActionResult
{
    public R4Mvc_Microsoft_AspNetCore_Mvc_RedirectToActionResult(string area, string controller, string action, string protocol = null): base (" ", " ", " ")
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }

    public string Controller
    {
        get;
        set;
    }

    public string Action
    {
        get;
        set;
    }

    public string Protocol
    {
        get;
        set;
    }

    public RouteValueDictionary RouteValueDictionary
    {
        get;
        set;
    }
}

[GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
internal partial class R4Mvc_Microsoft_AspNetCore_Mvc_RedirectToRouteResult : RedirectToRouteResult, IR4MvcActionResult
{
    public R4Mvc_Microsoft_AspNetCore_Mvc_RedirectToRouteResult(string area, string controller, string action, string protocol = null): base (null)
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }

    public string Controller
    {
        get;
        set;
    }

    public string Action
    {
        get;
        set;
    }

    public string Protocol
    {
        get;
        set;
    }

    public RouteValueDictionary RouteValueDictionary
    {
        get;
        set;
    }
}
#pragma warning restore 1591, 3008, 3009, 0108
